services:
  auto-codeql:
    container_name: auto-codeql
    image: auto-codeql:1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true